apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: blog-api
          image: blog-backend:latest
          imagePullPolicy: Never # 로컬 이미지 사용
          ports:
            - containerPort: 3001
          env:
            # ConfigMap에서 환경변수로 주입
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: ENVIRONMENT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: LOG_LEVEL
            - name: TIMEZONE
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: TIMEZONE
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: DB_NAME
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: API_PORT
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: CORS_ORIGIN
            - name: FEATURE_COMMENTS
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: FEATURE_COMMENTS
            - name: FEATURE_USER_REGISTRATION
              valueFrom:
                configMapKeyRef:
                  name: blog-config
                  key: FEATURE_USER_REGISTRATION

            # Secret에서 환경변수로 주입
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: JWT_SECRET

          # ConfigMap을 파일로 마운트
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

          # 헬스체크
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5

      volumes:
        - name: config-volume
          configMap:
            name: blog-config
            items:
              - key: app.properties
                path: app.properties

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
