apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: load-test-app
  template:
    metadata:
      labels:
        app: load-test-app
    spec:
      containers:
        - name: load-test
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m # κΈ°λ³Έ CPU μ”μ²­λ‰
              memory: 128Mi
            limits:
              cpu: 500m # μµλ€ CPU μ ν•
              memory: 256Mi
          # CPU λ¶€ν•λ¥Ό μƒμ„±ν•  μ μλ” κ°„λ‹¨ν• μ¤ν¬λ¦½νΈ μ¶”κ°€
          command: ["/bin/sh"]
          args:
            - -c
            - |
              cat > /usr/share/nginx/html/index.html << 'EOF'
              <!DOCTYPE html>
              <html><head><title>Load Test App</title></head>
              <body style="font-family: Arial; text-align: center; padding: 50px;">
                <h1>π€ Load Test Application</h1>
                <p>Pod: <span id="pod">Unknown</span></p>
                <button onclick="generateLoad()">CPU λ¶€ν• μƒμ„±</button>
                <div id="status"></div>
                <script>
                  function generateLoad() {
                    document.getElementById('status').innerHTML = 'CPU λ¶€ν• μƒμ„± μ¤‘...';
                    // CPU μ§‘μ•½μ  μ‘μ—… μ‹λ®¬λ μ΄μ…
                    for(let i = 0; i < 5000000; i++) {
                      Math.sqrt(Math.random());
                    }
                    document.getElementById('status').innerHTML = 'CPU λ¶€ν• μƒμ„± μ™„λ£!';
                  }
                  // Pod μ΄λ¦„ ν‘μ‹
                  fetch('/hostname')
                    .then(response => response.text())
                    .then(data => document.getElementById('pod').innerHTML = data)
                    .catch(() => document.getElementById('pod').innerHTML = 'nginx-pod');
                </script>
              </body></html>
              EOF

              # CPU λ¶€ν• μƒμ„± μ—”λ“ν¬μΈνΈ
              cat > /etc/nginx/conf.d/default.conf << 'EOF'
              server {
                  listen 80;
                  location / {
                      root /usr/share/nginx/html;
                      index index.html;
                  }
                  location /load {
                      return 200 "CPU load generated";
                      add_header Content-Type text/plain;
                  }
                  location /hostname {
                      return 200 "$hostname";
                      add_header Content-Type text/plain;
                  }
              }
              EOF

              nginx -g 'daemon off;'
---
apiVersion: v1
kind: Service
metadata:
  name: load-test-service
spec:
  selector:
    app: load-test-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
