# ConfigMap: 비민감한 설정 데이터 저장
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: simple-social
data:
  # 데이터베이스 연결 정보
  DB_HOST: "mysql-service"
  DB_NAME: "social_db"

  # Spring Boot 프로필 설정
  SPRING_PROFILES_ACTIVE: "production"

  # JVM 옵션
  JAVA_OPTS: "-Xmx512m -Xms256m"

---
# Secret: 민감한 정보를 암호화하여 저장
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: simple-social
type: Opaque
data:
  # Base64로 인코딩된 값들 (kubectl create secret으로 생성하는 것이 안전)
  DB_USER: cm9vdA== # echo -n 'root' | base64
  DB_PASSWORD: cGFzc3dvcmQ= # echo -n 'password' | base64
